//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivacyHide {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTranslate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrivacyHide.ResTranslate", typeof(ResTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Hide.
        /// </summary>
        internal static string ___Απόκρυψη {
            get {
                return ResourceManager.GetString("<< Απόκρυψη", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a trial version of the application. Press the &quot;Buy now&quot; button to buy a license..
        /// </summary>
        internal static string Add_new_search_item_to_project {
            get {
                return ResourceManager.GetString("Add new search item to project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this Folder and all its Subfolders and Files ?.
        /// </summary>
        internal static string Are_you_sure_that_you_want_to_delete_this_Folder_and_all_its_Subfolders_and_Files__ {
            get {
                return ResourceManager.GetString("Are you sure that you want to delete this Folder and all its Subfolders and Files" +
                        " ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cm.
        /// </summary>
        internal static string Cm {
            get {
                return ResourceManager.GetString("Cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Successful! Please restart the application..
        /// </summary>
        internal static string Continue_activated_search_ {
            get {
                return ResourceManager.GetString("Continue activated search?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        internal static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Position.
        /// </summary>
        internal static string Current_Position {
            get {
                return ResourceManager.GetString("Current Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        internal static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Registration ! Please contact the author of the application..
        /// </summary>
        internal static string Direct_search_started {
            get {
                return ResourceManager.GetString("Direct search started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop the Photos Here.
        /// </summary>
        internal static string Drag_and_Drop_the_Photos_Here {
            get {
                return ResourceManager.GetString("Drag and Drop the Photos Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test period of the application has expired. Press the &quot;Buy now&quot; button to buy a license..
        /// </summary>
        internal static string Edit_4dots_Project {
            get {
                return ResourceManager.GetString("Edit 4dots Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Unable to register. Please contact the author of the application if this error persists..
        /// </summary>
        internal static string Erroneous_search_2 {
            get {
                return ResourceManager.GetString("Erroneous search 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not copy Derm Expert Lite Database to new Client Images Directory !.
        /// </summary>
        internal static string Error__Could_not_copy_Derm_Expert_Lite_Database_to_new_Client_Images_Directory__ {
            get {
                return ResourceManager.GetString("Error. Could not copy Derm Expert Lite Database to new Client Images Directory !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not move Photo.
        /// </summary>
        internal static string Error__Could_not_move_Photo {
            get {
                return ResourceManager.GetString("Error. Could not move Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not save Comments !.
        /// </summary>
        internal static string Error__Could_not_save_Comments__ {
            get {
                return ResourceManager.GetString("Error. Could not save Comments !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not send Email !.
        /// </summary>
        internal static string Error__Could_not_send_Email__ {
            get {
                return ResourceManager.GetString("Error. Could not send Email !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not send Questionnaire !.
        /// </summary>
        internal static string Error__Could_not_send_Questionnaire__ {
            get {
                return ResourceManager.GetString("Error. Could not send Questionnaire !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 1.
        /// </summary>
        internal static string Error_1 {
            get {
                return ResourceManager.GetString("Error 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS.
        /// </summary>
        internal static string Error_12 {
            get {
                return ResourceManager.GetString("Error 12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 4.
        /// </summary>
        internal static string Error_4 {
            get {
                return ResourceManager.GetString("Error 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not create Folder !.
        /// </summary>
        internal static string Error_could_not_create_Folder__ {
            get {
                return ResourceManager.GetString("Error could not create Folder !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not delete Folder !.
        /// </summary>
        internal static string Error_could_not_delete_Folder__ {
            get {
                return ResourceManager.GetString("Error could not delete Folder !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not rename Folder !.
        /// </summary>
        internal static string Error_could_not_rename_Folder__ {
            get {
                return ResourceManager.GetString("Error could not rename Folder !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Days :.
        /// </summary>
        internal static string Error_during_search_startup {
            get {
                return ResourceManager.GetString("Error during search startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export also Subfolder(s) Photos ?.
        /// </summary>
        internal static string Export_also_Subfolder_s__Photos__ {
            get {
                return ResourceManager.GetString("Export also Subfolder(s) Photos ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Photo.
        /// </summary>
        internal static string First_Photo {
            get {
                return ResourceManager.GetString("First Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Name.
        /// </summary>
        internal static string Folder_Name {
            get {
                return ResourceManager.GetString("Folder Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold down the Control Key and then make a Left Mouse Click on the Photo to Zoom In or make a Right Mouse Click to Zoom Out.\n\nTo do a Parallel Zoom i.e. Zoom both Photos at exactly the same Point at the same Time , hold down the Shift Key and do a Left or Right Mouse Click..
        /// </summary>
        internal static string Hold_down_the_Control_Key_and_then_make_a_Left_Mouse_Click_on_the_Photo_to_Zoom_In_or_make_a_Right_Mouse_Click_to_Zoom_Out__n_nTo_do_a_Parallel_Zoom_i_e__Zoom_both_Photos_at_exactly_the_same_Point_at_the_same_Time___hold_down_the_Shift_Key_and_do_a_Left_or_Right_Mouse_Click_ {
            get {
                return ResourceManager.GetString(@"Hold down the Control Key and then make a Left Mouse Click on the Photo to Zoom In or make a Right Mouse Click to Zoom Out.\n\nTo do a Parallel Zoom i.e. Zoom both Photos at exactly the same Point at the same Time , hold down the Shift Key and do a Left or Right Mouse Click.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3ew125a23.
        /// </summary>
        internal static string Import_search_result {
            get {
                return ResourceManager.GetString("Import search result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        internal static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRFDf.
        /// </summary>
        internal static string Init_Project {
            get {
                return ResourceManager.GetString("Init Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key was registered. Please restart the application..
        /// </summary>
        internal static string Initial_Failure_Object {
            get {
                return ResourceManager.GetString("Initial Failure Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser / Lights Λεπτομέρειες.
        /// </summary>
        internal static string Laser___Lights_Λεπτομέρειες {
            get {
                return ResourceManager.GetString("Laser / Lights Λεπτομέρειες", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageTitle.
        /// </summary>
        internal static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageTitle7.
        /// </summary>
        internal static string MessageTitle7 {
            get {
                return ResourceManager.GetString("MessageTitle7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageTitle8.
        /// </summary>
        internal static string MessageTitle8 {
            get {
                return ResourceManager.GetString("MessageTitle8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images were found !.
        /// </summary>
        internal static string No_images_were_found__ {
            get {
                return ResourceManager.GetString("No images were found !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully !.
        /// </summary>
        internal static string Operation_completed_successfully__ {
            get {
                return ResourceManager.GetString("Operation completed successfully !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixels.
        /// </summary>
        internal static string Pixels {
            get {
                return ResourceManager.GetString("Pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out our Questionnaire !.
        /// </summary>
        internal static string Please_fill_out_our_Questionnaire__ {
            get {
                return ResourceManager.GetString("Please fill out our Questionnaire !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a Recipient.
        /// </summary>
        internal static string Please_insert_a_Recipient {
            get {
                return ResourceManager.GetString("Please insert a Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a Subject !.
        /// </summary>
        internal static string Please_insert_a_Subject__ {
            get {
                return ResourceManager.GetString("Please insert a Subject !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a valid Filename.
        /// </summary>
        internal static string Please_insert_a_valid_Filename {
            get {
                return ResourceManager.GetString("Please insert a valid Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a valid Foldername.
        /// </summary>
        internal static string Please_insert_a_valid_Foldername {
            get {
                return ResourceManager.GetString("Please insert a valid Foldername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open two Photos before trying to print both Photos !.
        /// </summary>
        internal static string Please_open_two_Photos_before_trying_to_print_both_Photos__ {
            get {
                return ResourceManager.GetString("Please open two Photos before trying to print both Photos !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the Application in order that the Settings take effect !.
        /// </summary>
        internal static string Please_restart_the_Application_in_order_that_the_Settings_take_effect__ {
            get {
                return ResourceManager.GetString("Please restart the Application in order that the Settings take effect !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a Folder Name.
        /// </summary>
        internal static string Please_specify_a_Folder_Name {
            get {
                return ResourceManager.GetString("Please specify a Folder Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid Client Images Folder !.
        /// </summary>
        internal static string Please_specify_a_valid_Client_Images_Folder__ {
            get {
                return ResourceManager.GetString("Please specify a valid Client Images Folder !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid New Images Folder !.
        /// </summary>
        internal static string Please_specify_a_valid_New_Images_Folder__ {
            get {
                return ResourceManager.GetString("Please specify a valid New Images Folder !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace string process started.
        /// </summary>
        internal static string Replace_string_process_started {
            get {
                return ResourceManager.GetString("Replace string process started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID REGISTRATION.
        /// </summary>
        internal static string Search_duration_process {
            get {
                return ResourceManager.GetString("Search duration process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Photo.
        /// </summary>
        internal static string Second_Photo {
            get {
                return ResourceManager.GetString("Second Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooting Date.
        /// </summary>
        internal static string Shooting_Date {
            get {
                return ResourceManager.GetString("Shooting Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slideshow.
        /// </summary>
        internal static string Slideshow {
            get {
                return ResourceManager.GetString("Slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Slideshow requires at least two Photos available in order to work !.
        /// </summary>
        internal static string The_Slideshow_requires_at_least_two_Photos_available_in_order_to_work__ {
            get {
                return ResourceManager.GetString("The Slideshow requires at least two Photos available in order to work !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To crop an Area of the Photo , hold down the Left Mouse Button on the Upper Left Corner of the Area to be croped. Then , while holding down the Left Mouse Button , move to the Right Lower Corner of the Area and leave the Mouse Button. If you are satisfied with the Result , click with the Mouse on the Area , or press Escape to clear..
        /// </summary>
        internal static string To_crop_an_Area_of_the_Photo___hold_down_the_Left_Mouse_Button_on_the_Upper_Left_Corner_of_the_Area_to_be_croped__Then___while_holding_down_the_Left_Mouse_Button___move_to_the_Right_Lower_Corner_of_the_Area_and_leave_the_Mouse_Button__If_you_are_satisfied_with_the_Result___click_with_the_Mouse_on_the_Area___or_press_Escape_to_clear_ {
            get {
                return ResourceManager.GetString(@"To crop an Area of the Photo , hold down the Left Mouse Button on the Upper Left Corner of the Area to be croped. Then , while holding down the Left Mouse Button , move to the Right Lower Corner of the Area and leave the Mouse Button. If you are satisfied with the Result , click with the Mouse on the Area , or press Escape to clear.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST.
        /// </summary>
        internal static string Uniform_process {
            get {
                return ResourceManager.GetString("Uniform process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified Error.
        /// </summary>
        internal static string Unspecified_Error {
            get {
                return ResourceManager.GetString("Unspecified Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning ! Could not remove Database from old Client Images Directory !.
        /// </summary>
        internal static string Warning___Could_not_remove_Database_from_old_Client_Images_Directory__ {
            get {
                return ResourceManager.GetString("Warning ! Could not remove Database from old Client Images Directory !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error.
        /// </summary>
        internal static string Ακαθόριστο_Σφάλμα {
            get {
                return ResourceManager.GetString("Ακαθόριστο Σφάλμα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Άλλα.
        /// </summary>
        internal static string Άλλα {
            get {
                return ResourceManager.GetString("Άλλα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRVH-1.0.
        /// </summary>
        internal static string Αλλαγή_Ονόματος {
            get {
                return ResourceManager.GetString("Αλλαγή Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string Αλλαγή_στοιχείων_εικόνας {
            get {
                return ResourceManager.GetString("Αλλαγή στοιχείων εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24e12gvf.
        /// </summary>
        internal static string Αλλαγή_Φίλτρου_Εικόνας {
            get {
                return ResourceManager.GetString("Αλλαγή Φίλτρου Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αναισθησία.
        /// </summary>
        internal static string Αναισθησία {
            get {
                return ResourceManager.GetString("Αναισθησία", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?optionfile=.
        /// </summary>
        internal static string Ανανέωση_Εικόνας {
            get {
                return ResourceManager.GetString("Ανανέωση Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        internal static string Αντίθεση {
            get {
                return ResourceManager.GetString("Αντίθεση", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Αποθήκευση {
            get {
                return ResourceManager.GetString("Αποθήκευση", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Άρρεν.
        /// </summary>
        internal static string Άρρεν {
            get {
                return ResourceManager.GetString("Άρρεν", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Αρχείο {
            get {
                return ResourceManager.GetString("Αρχείο", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αρχίζει με.
        /// </summary>
        internal static string Αρχίζει_με {
            get {
                return ResourceManager.GetString("Αρχίζει με", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αρχίζουν με.
        /// </summary>
        internal static string Αρχίζουν_με {
            get {
                return ResourceManager.GetString("Αρχίζουν με", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Βασικά Στοιχεία.
        /// </summary>
        internal static string Βασικά_Στοιχεία {
            get {
                return ResourceManager.GetString("Βασικά Στοιχεία", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Βιοψία.
        /// </summary>
        internal static string Βιοψία {
            get {
                return ResourceManager.GetString("Βιοψία", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Βλάβη.
        /// </summary>
        internal static string Βλάβη {
            get {
                return ResourceManager.GetString("Βλάβη", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Βλάβη : .
        /// </summary>
        internal static string Βλάβη___ {
            get {
                return ResourceManager.GetString("Βλάβη : ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found.
        /// </summary>
        internal static string Βρέθηκαν {
            get {
                return ResourceManager.GetString("Βρέθηκαν", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δε βρέθηκε συμβατή Φωτογραφική Μηχανή ! Παρακαλώ συνδέστε μία Φωτογραφική Μηχανή που έχει δυνατότητα.
        /// </summary>
        internal static string Δε_βρέθηκε_συμβατή_Φωτογραφική_Μηχανή___Παρακαλώ_συνδέστε_μία_Φωτογραφική_Μηχανή_που_έχει_δυνατότητα {
            get {
                return ResourceManager.GetString("Δε βρέθηκε συμβατή Φωτογραφική Μηχανή ! Παρακαλώ συνδέστε μία Φωτογραφική Μηχανή " +
                        "που έχει δυνατότητα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν βρέθηκαν νέες Φωτογραφίες στον Φάκελο του Πελάτη !.
        /// </summary>
        internal static string Δεν_βρέθηκαν_νέες_Φωτογραφίες_στον_Φάκελο_του_Πελάτη__ {
            get {
                return ResourceManager.GetString("Δεν βρέθηκαν νέες Φωτογραφίες στον Φάκελο του Πελάτη !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν ήταν δυνατή η αντιγραφή των Αρχείων Εξαγωγής !.
        /// </summary>
        internal static string Δεν_ήταν_δυνατή_η_αντιγραφή_των_Αρχείων_Εξαγωγής__ {
            get {
                return ResourceManager.GetString("Δεν ήταν δυνατή η αντιγραφή των Αρχείων Εξαγωγής !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send email.
        /// </summary>
        internal static string Δεν_ήταν_δυνατή_η_αποστολή_ηλεκτρονικού_μηνύματος {
            get {
                return ResourceManager.GetString("Δεν ήταν δυνατή η αποστολή ηλεκτρονικού μηνύματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν ήταν δυνατή η αφαίρεση της Φωτογραφίας από τη Βλάβη !.
        /// </summary>
        internal static string Δεν_ήταν_δυνατή_η_αφαίρεση_της_Φωτογραφίας_από_τη_Βλάβη__ {
            get {
                return ResourceManager.GetString("Δεν ήταν δυνατή η αφαίρεση της Φωτογραφίας από τη Βλάβη !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create directory.
        /// </summary>
        internal static string Δεν_ήταν_δυνατή_η_δημιουργία_του_καταλόγου {
            get {
                return ResourceManager.GetString("Δεν ήταν δυνατή η δημιουργία του καταλόγου", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the Export Folder !.
        /// </summary>
        internal static string Δεν_ήταν_δυνατή_η_δημιουργία_του_Φακέλου_Εξαγωγής__ {
            get {
                return ResourceManager.GetString("Δεν ήταν δυνατή η δημιουργία του Φακέλου Εξαγωγής !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Delete!.
        /// </summary>
        internal static string Δεν_ήταν_δυνατή_η_Διαγραφή__ {
            get {
                return ResourceManager.GetString("Δεν ήταν δυνατή η Διαγραφή !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Update!.
        /// </summary>
        internal static string Δεν_ήταν_δυνατή_η_Ενημέρωση__ {
            get {
                return ResourceManager.GetString("Δεν ήταν δυνατή η Ενημέρωση !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the database!.
        /// </summary>
        internal static string Δεν_ήταν_δυνατή_η_ενημέρωση_της_βάσης_δεδομένων__ {
            get {
                return ResourceManager.GetString("Δεν ήταν δυνατή η ενημέρωση της βάσης δεδομένων !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not update data !.
        /// </summary>
        internal static string Δεν_ήταν_δυνατή_η_Ενημέρωση_των_Στοιχείων__ {
            get {
                return ResourceManager.GetString("Δεν ήταν δυνατή η Ενημέρωση των Στοιχείων !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν ήταν δυνατή η Εξαγωγή σε Excel.
        /// </summary>
        internal static string Δεν_ήταν_δυνατή_η_Εξαγωγή_σε_Excel {
            get {
                return ResourceManager.GetString("Δεν ήταν δυνατή η Εξαγωγή σε Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not export to PowerPoint.
        /// </summary>
        internal static string Δεν_ήταν_δυνατή_η_Εξαγωγή_στο_PowerPoint {
            get {
                return ResourceManager.GetString("Δεν ήταν δυνατή η Εξαγωγή στο PowerPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν ήταν δυνατή η Εξαγωγή στο Word.
        /// </summary>
        internal static string Δεν_ήταν_δυνατή_η_Εξαγωγή_στο_Word {
            get {
                return ResourceManager.GetString("Δεν ήταν δυνατή η Εξαγωγή στο Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move folder !.
        /// </summary>
        internal static string Δεν_ήταν_δυνατή_η_μετακίνηση_του_φακέλου__ {
            get {
                return ResourceManager.GetString("Δεν ήταν δυνατή η μετακίνηση του φακέλου !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not display Data.
        /// </summary>
        internal static string Δεν_ήταν_δυνατή_η_Προβολή_των_Στοιχείων {
            get {
                return ResourceManager.GetString("Δεν ήταν δυνατή η Προβολή των Στοιχείων", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν Περιέχει.
        /// </summary>
        internal static string Δεν_Περιέχει {
            get {
                return ResourceManager.GetString("Δεν Περιέχει", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δεν περιέχουν.
        /// </summary>
        internal static string Δεν_περιέχουν {
            get {
                return ResourceManager.GetString("Δεν περιέχουν", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δερματοσκοπικές Φωτογραφίες.
        /// </summary>
        internal static string Δερματοσκοπικές_Φωτογραφίες {
            get {
                return ResourceManager.GetString("Δερματοσκοπικές Φωτογραφίες", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δερματοσκοπική.
        /// </summary>
        internal static string Δερματοσκοπική {
            get {
                return ResourceManager.GetString("Δερματοσκοπική", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Photo.
        /// </summary>
        internal static string Δεύτερη_Εικόνα {
            get {
                return ResourceManager.GetString("Δεύτερη Εικόνα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        internal static string Διάγνωση {
            get {
                return ResourceManager.GetString("Διάγνωση", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγραφή σπίλου ;.
        /// </summary>
        internal static string Διαγραφή_σπίλου__ {
            get {
                return ResourceManager.GetString("Διαγραφή σπίλου ;", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions (Pixels).
        /// </summary>
        internal static string Διαστάσεις__Pixels_ {
            get {
                return ResourceManager.GetString("Διαστάσεις (Pixels)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διάφορο Από.
        /// </summary>
        internal static string Διάφορο_Από {
            get {
                return ResourceManager.GetString("Διάφορο Από", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διάφορος Από.
        /// </summary>
        internal static string Διάφορος_Από {
            get {
                return ResourceManager.GetString("Διάφορος Από", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If many users will use the application , use a shared folder!.
        /// </summary>
        internal static string Εάν_θα_χρησιμοποιήσουν_την_Εφαρμογή_πολλοί_Χρήστες___χρησιμοποιήστε_κάποιον_Κοινόχρηστο_Φάκελο__ {
            get {
                return ResourceManager.GetString("Εάν θα χρησιμοποιήσουν την Εφαρμογή πολλοί Χρήστες , χρησιμοποιήστε κάποιον Κοινό" +
                        "χρηστο Φάκελο !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you select the Desktop Folder as the Application Folder , it is possible that the Application will not work for other Users..
        /// </summary>
        internal static string Εάν_χρησιμοποιήσετε_ως_Φάκελο_της_Εφαρμογής_τον_Φάκελο_της_Επιφάνειας_Εργασίας__πιθανόν_να_μη_λειτουργεί_σωστά_η_Εφαρμογή_για_τους_άλλους_Χρήστες_του_Υπολογιστή_ {
            get {
                return ResourceManager.GetString("Εάν χρησιμοποιήσετε ως Φάκελο της Εφαρμογής τον Φάκελο της Επιφάνειας Εργασίας, π" +
                        "ιθανόν να μη λειτουργεί σωστά η Εφαρμογή για τους άλλους Χρήστες του Υπολογιστή." +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24e40dde.
        /// </summary>
        internal static string Εισαγωγή_Εικόνας {
            get {
                return ResourceManager.GetString("Εισαγωγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είστε σίγουροι ότι θέλετε να διαγράψετε αυτή τη Νόσο / Αιτιολογία και όλα τα στοιχεία της ;.
        /// </summary>
        internal static string Είστε_σίγουροι_ότι_θέλετε_να_διαγράψετε_αυτή_τη_Νόσο___Αιτιολογία_και_όλα_τα_στοιχεία_της__ {
            get {
                return ResourceManager.GetString("Είστε σίγουροι ότι θέλετε να διαγράψετε αυτή τη Νόσο / Αιτιολογία και όλα τα στοι" +
                        "χεία της ;", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είστε σίγουροι ότι θέλετε να διαγράψετε αυτή την Παρούσα Νόσο και όλα τα στοιχεία της ;.
        /// </summary>
        internal static string Είστε_σίγουροι_ότι_θέλετε_να_διαγράψετε_αυτή_την_Παρούσα_Νόσο_και_όλα_τα_στοιχεία_της__ {
            get {
                return ResourceManager.GetString("Είστε σίγουροι ότι θέλετε να διαγράψετε αυτή την Παρούσα Νόσο και όλα τα στοιχεία" +
                        " της ;", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete completely the Photo ?.
        /// </summary>
        internal static string Είστε_σίγουροι_ότι_θέλετε_να_διαγράψετε_πλήρως_την_φωτογραφία__ {
            get {
                return ResourceManager.GetString("Είστε σίγουροι ότι θέλετε να διαγράψετε πλήρως την φωτογραφία ;", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είστε σίγουροι ότι θέλετε να διαγράψετε το σπίλο ;.
        /// </summary>
        internal static string Είστε_σίγουροι_ότι_θέλετε_να_διαγράψετε_το_σπίλο__ {
            get {
                return ResourceManager.GetString("Είστε σίγουροι ότι θέλετε να διαγράψετε το σπίλο ;", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to use the Desktop Folder ?.
        /// </summary>
        internal static string Είστε_σίγουρος_ότι_θέλετε_να_χρησιμοποιήσετε_τον_Φάκελο_της_Επιφάνειας_Εργασίας__ {
            get {
                return ResourceManager.GetString("Είστε σίγουρος ότι θέλετε να χρησιμοποιήσετε τον Φάκελο της Επιφάνειας Εργασίας ;" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &gt;&gt;.
        /// </summary>
        internal static string Εμφάνιση___ {
            get {
                return ResourceManager.GetString("Εμφάνιση >>", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asd321e5.
        /// </summary>
        internal static string Εναλλαγή_Εικόνας {
            get {
                return ResourceManager.GetString("Εναλλαγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επεμβάσεις Laser.
        /// </summary>
        internal static string Επεμβάσεις_Laser {
            get {
                return ResourceManager.GetString("Επεμβάσεις Laser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλέξτε πρώτα μία Νόσο / Αιτιολογία !.
        /// </summary>
        internal static string Επιλέξτε_πρώτα_μία_Νόσο___Αιτιολογία__ {
            get {
                return ResourceManager.GetString("Επιλέξτε πρώτα μία Νόσο / Αιτιολογία !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επιλέξτε πρώτα μία Παρούσα Νόσο !.
        /// </summary>
        internal static string Επιλέξτε_πρώτα_μία_Παρούσα_Νόσο__ {
            get {
                return ResourceManager.GetString("Επιλέξτε πρώτα μία Παρούσα Νόσο !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Επιλογές {
            get {
                return ResourceManager.GetString("Επιλογές", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επισκέψεις.
        /// </summary>
        internal static string Επισκέψεις {
            get {
                return ResourceManager.GetString("Επισκέψεις", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully !.
        /// </summary>
        internal static string Η_λειτουργία_εκτελέστηκε_επιτυχώς__ {
            get {
                return ResourceManager.GetString("Η λειτουργία εκτελέστηκε επιτυχώς !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation executed successfully! Please restart the application!.
        /// </summary>
        internal static string Η_λειτουργία_εκτελέστηκε_επιτυχώς____n_n_Παρακαλώ_επαναεκκινήστε_την_εφαρμογή__ {
            get {
                return ResourceManager.GetString("Η λειτουργία εκτελέστηκε επιτυχώς ! \\n\\n Παρακαλώ επαναεκκινήστε την εφαρμογή !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slide show takes at least two photos (dermatoscopic or normal view photos) to work!.
        /// </summary>
        internal static string Η_Προβολή_Παρουσίασης_χρειάζεται_τουλάχιστον_δύο_φωτογραφίες__δερματοσκοπικές_ή_κατοπτικές__προκειμένου_να_λειτουργήσει__ {
            get {
                return ResourceManager.GetString("Η Προβολή Παρουσίασης χρειάζεται τουλάχιστον δύο φωτογραφίες (δερματοσκοπικές ή κ" +
                        "ατοπτικές) προκειμένου να λειτουργήσει !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημ/νία Επέμβασης.
        /// </summary>
        internal static string Ημ_νία_Επέμβασης {
            get {
                return ResourceManager.GetString("Ημ/νία Επέμβασης", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Ημερομηνία {
            get {
                return ResourceManager.GetString("Ημερομηνία", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημερομηνία Γεννήσεως.
        /// </summary>
        internal static string Ημερομηνία_Γεννήσεως {
            get {
                return ResourceManager.GetString("Ημερομηνία Γεννήσεως", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooting Date.
        /// </summary>
        internal static string Ημερομηνία_Λήψεως {
            get {
                return ResourceManager.GetString("Ημερομηνία Λήψεως", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Θέλετε πλήρη διαγραφή πελάτη (διαγραφή των στοιχείων του καθώς και των φωτογραφιών του) ;.
        /// </summary>
        internal static string Θέλετε_πλήρη_διαγραφή_πελάτη__διαγραφή_των_στοιχείων_του_καθώς_και_των_φωτογραφιών_του___ {
            get {
                return ResourceManager.GetString("Θέλετε πλήρη διαγραφή πελάτη (διαγραφή των στοιχείων του καθώς και των φωτογραφιώ" +
                        "ν του) ;", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Θήλυ.
        /// </summary>
        internal static string Θήλυ {
            get {
                return ResourceManager.GetString("Θήλυ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ίσο με.
        /// </summary>
        internal static string Ίσο_με {
            get {
                return ResourceManager.GetString("Ίσο με", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ίσος με.
        /// </summary>
        internal static string Ίσος_με {
            get {
                return ResourceManager.GetString("Ίσος με", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ιστορικό Αλλεργικών Αντιδράσεων.
        /// </summary>
        internal static string Ιστορικό_Αλλεργικών_Αντιδράσεων {
            get {
                return ResourceManager.GetString("Ιστορικό Αλλεργικών Αντιδράσεων", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ιστορικό Ασθενούς.
        /// </summary>
        internal static string Ιστορικό_Ασθενούς {
            get {
                return ResourceManager.GetString("Ιστορικό Ασθενούς", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |||***DTT***|||.
        /// </summary>
        internal static string Καθορισμός_Ονόματος {
            get {
                return ResourceManager.GetString("Καθορισμός Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατοπτικές Φωτογραφίες.
        /// </summary>
        internal static string Κατοπτικές_Φωτογραφίες {
            get {
                return ResourceManager.GetString("Κατοπτικές Φωτογραφίες", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατοπτική.
        /// </summary>
        internal static string Κατοπτική {
            get {
                return ResourceManager.GetString("Κατοπτική", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λήψη Φαρμάκων.
        /// </summary>
        internal static string Λήψη_Φαρμάκων {
            get {
                return ResourceManager.GetString("Λήψη Φαρμάκων", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λοιμώδη Νοσήματα.
        /// </summary>
        internal static string Λοιμώδη_Νοσήματα {
            get {
                return ResourceManager.GetString("Λοιμώδη Νοσήματα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μεγαλύτερο Από.
        /// </summary>
        internal static string Μεγαλύτερο_Από {
            get {
                return ResourceManager.GetString("Μεγαλύτερο Από", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μεγαλύτερος Από.
        /// </summary>
        internal static string Μεγαλύτερος_Από {
            get {
                return ResourceManager.GetString("Μεγαλύτερος Από", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (KB).
        /// </summary>
        internal static string Μέγεθος__KB_ {
            get {
                return ResourceManager.GetString("Μέγεθος (KB)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move files to the new Folder ?.
        /// </summary>
        internal static string Μετακίνηση_Αρχείων_στον_νέο_Φάκελο__ {
            get {
                return ResourceManager.GetString("Μετακίνηση Αρχείων στον νέο Φάκελο ;", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Files of the current Photo Folder to the new Folder? If the Files already exist in the new Folder ,press No..
        /// </summary>
        internal static string Μετακίνηση_των_Αρχείων_τωρινού_Φακέλου_Φωτογραφιών_στον_καινούργιο_Φάκελο___Εάν_υπάρχουν_ήδη_τα_Αρχεία_στον_νέο_Φάκελο_πατήστει_Όχι_ {
            get {
                return ResourceManager.GetString("Μετακίνηση των Αρχείων τωρινού Φακέλου Φωτογραφιών στον καινούργιο Φάκελο ; Εάν υ" +
                        "πάρχουν ήδη τα Αρχεία στον νέο Φάκελο πατήστει Όχι.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this Message again.
        /// </summary>
        internal static string Μη_ξαναδείξεις_αυτό_το_μήνυμα {
            get {
                return ResourceManager.GetString("Μη ξαναδείξεις αυτό το μήνυμα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Photo.
        /// </summary>
        internal static string Μία_Εικόνα {
            get {
                return ResourceManager.GetString("Μία Εικόνα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μικρότερο Από.
        /// </summary>
        internal static string Μικρότερο_Από {
            get {
                return ResourceManager.GetString("Μικρότερο Από", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μικρότερος Από.
        /// </summary>
        internal static string Μικρότερος_Από {
            get {
                return ResourceManager.GetString("Μικρότερος Από", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e9r4hFfEedffYFUfth123458.
        /// </summary>
        internal static string Μορφοποίηση_Εικόνας {
            get {
                return ResourceManager.GetString("Μορφοποίηση Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\\DtMsg.
        /// </summary>
        internal static string Νέα_Εικόνα {
            get {
                return ResourceManager.GetString("Νέα Εικόνα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Νόσος / Αιτιολογία.
        /// </summary>
        internal static string Νόσος___Αιτιολογία {
            get {
                return ResourceManager.GetString("Νόσος / Αιτιολογία", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application settings have changed successfully! Please restart the application..
        /// </summary>
        internal static string Οι_Ρυθμίσεις_της_Εφαρμογής_άλλαξαν_επιτυχώς___Παρακαλώ_επανεκκινήστε_την_Εφαρμογή_ {
            get {
                return ResourceManager.GetString("Οι Ρυθμίσεις της Εφαρμογής άλλαξαν επιτυχώς ! Παρακαλώ επανεκκινήστε την Εφαρμογή" +
                        " ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΟΚ.
        /// </summary>
        internal static string ΟΚ {
            get {
                return ResourceManager.GetString("ΟΚ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα.
        /// </summary>
        internal static string Όνομα {
            get {
                return ResourceManager.GetString("Όνομα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ αποθηκεύστε πρώτα τον πελάτη προτού καθορίσετε κάποια εικόνα για αυτόν.
        /// </summary>
        internal static string Παρακαλώ_αποθηκεύστε_πρώτα_τον_πελάτη_προτού_καθορίσετε_κάποια_εικόνα_για_αυτόν {
            get {
                return ResourceManager.GetString("Παρακαλώ αποθηκεύστε πρώτα τον πελάτη προτού καθορίσετε κάποια εικόνα για αυτόν", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the Registration Information.
        /// </summary>
        internal static string Παρακαλώ_εισάγετε_ένα_Όνομα_για_τα_στοιχεία_εγγραφής {
            get {
                return ResourceManager.GetString("Παρακαλώ εισάγετε ένα Όνομα για τα στοιχεία εγγραφής", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the number of licenses you have purchased.
        /// </summary>
        internal static string Παρακαλώ_εισάγετε_έναν_Αριθμό_Αδειών_Χρήσης_που_έχετε_αγοράσει {
            get {
                return ResourceManager.GetString("Παρακαλώ εισάγετε έναν Αριθμό Αδειών Χρήσης που έχετε αγοράσει", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date!.
        /// </summary>
        internal static string Παρακαλώ_εισάγετε_κάποια_Έγκυρη_Ημερομηνία__ {
            get {
                return ResourceManager.GetString("Παρακαλώ εισάγετε κάποια Έγκυρη Ημερομηνία !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an Email as a recipient.
        /// </summary>
        internal static string Παρακαλώ_εισάγετε_κάποιο_Email_για_Λήπτη {
            get {
                return ResourceManager.GetString("Παρακαλώ εισάγετε κάποιο Email για Λήπτη", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Subject.
        /// </summary>
        internal static string Παρακαλώ_εισάγετε_κάποιο_Θέμα {
            get {
                return ResourceManager.GetString("Παρακαλώ εισάγετε κάποιο Θέμα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ εισάγετε κάποιο Ποσό !.
        /// </summary>
        internal static string Παρακαλώ_εισάγετε_κάποιο_Ποσό__ {
            get {
                return ResourceManager.GetString("Παρακαλώ εισάγετε κάποιο Ποσό !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ εισάγετε κάποιον Αριθμό !.
        /// </summary>
        internal static string Παρακαλώ_εισάγετε_κάποιον_Αριθμό__ {
            get {
                return ResourceManager.GetString("Παρακαλώ εισάγετε κάποιον Αριθμό !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ εισάγετε Ονοματεπώνυμο Πελάτη !.
        /// </summary>
        internal static string Παρακαλώ_εισάγετε_Ονοματεπώνυμο_Πελάτη__ {
            get {
                return ResourceManager.GetString("Παρακαλώ εισάγετε Ονοματεπώνυμο Πελάτη !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ εισάγετε Τηλέφωνο Πελάτη !.
        /// </summary>
        internal static string Παρακαλώ_εισάγετε_Τηλέφωνο_Πελάτη__ {
            get {
                return ResourceManager.GetString("Παρακαλώ εισάγετε Τηλέφωνο Πελάτη !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the key exactly as it was sent to you !.
        /// </summary>
        internal static string Παρακαλώ_εισάγετε_το_κλειδί_όπως_σας_αποστάλθηκε__ {
            get {
                return ResourceManager.GetString("Παρακαλώ εισάγετε το κλειδί όπως σας αποστάλθηκε !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Photos Folder !.
        /// </summary>
        internal static string Παρακαλώ_επιλέξτε_ένα_Φάκελο_αποθήκευσης_Φωτογραφιών__ {
            get {
                return ResourceManager.GetString("Παρακαλώ επιλέξτε ένα Φάκελο αποθήκευσης Φωτογραφιών !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder !.
        /// </summary>
        internal static string Παρακαλώ_επιλέξτε_έναν_φάκελο__ {
            get {
                return ResourceManager.GetString("Παρακαλώ επιλέξτε έναν φάκελο !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ επιλέξτε μία Βλάβη αντιστοίχισης για τη Φωτογραφία .
        /// </summary>
        internal static string Παρακαλώ_επιλέξτε_μία_Βλάβη_αντιστοίχισης_για_τη_Φωτογραφία_ {
            get {
                return ResourceManager.GetString("Παρακαλώ επιλέξτε μία Βλάβη αντιστοίχισης για τη Φωτογραφία ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ επιλέξτε μία Βλάβη για τη Φωτογραφία :.
        /// </summary>
        internal static string Παρακαλώ_επιλέξτε_μία_Βλάβη_για_τη_Φωτογραφία__ {
            get {
                return ResourceManager.GetString("Παρακαλώ επιλέξτε μία Βλάβη για τη Φωτογραφία :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ επιλέξτε μία Περιοχή Σώματος για τη Φωτογραφία :.
        /// </summary>
        internal static string Παρακαλώ_επιλέξτε_μία_Περιοχή_Σώματος_για_τη_Φωτογραφία__ {
            get {
                return ResourceManager.GetString("Παρακαλώ επιλέξτε μία Περιοχή Σώματος για τη Φωτογραφία :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ επιλέξτε μία Περιοχή Σώματος για το Πλαίσιο .
        /// </summary>
        internal static string Παρακαλώ_επιλέξτε_μία_Περιοχή_Σώματος_για_το_Πλαίσιο_ {
            get {
                return ResourceManager.GetString("Παρακαλώ επιλέξτε μία Περιοχή Σώματος για το Πλαίσιο ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ επιλέξτε πρώτα έναν Πελάτη προτού στείλετε Φωτογραφίες.
        /// </summary>
        internal static string Παρακαλώ_επιλέξτε_πρώτα_έναν_Πελάτη_προτού_στείλετε_Φωτογραφίες {
            get {
                return ResourceManager.GetString("Παρακαλώ επιλέξτε πρώτα έναν Πελάτη προτού στείλετε Φωτογραφίες", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ επιλέξτε πρώτα μία βλάβη !.
        /// </summary>
        internal static string Παρακαλώ_επιλέξτε_πρώτα_μία_βλάβη__ {
            get {
                return ResourceManager.GetString("Παρακαλώ επιλέξτε πρώτα μία βλάβη !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ επιλέξτε πρώτα μία Γραμμή.
        /// </summary>
        internal static string Παρακαλώ_επιλέξτε_πρώτα_μία_Γραμμή {
            get {
                return ResourceManager.GetString("Παρακαλώ επιλέξτε πρώτα μία Γραμμή", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ επιλέξτε πρώτα μία Νόσο / Αιτιολογία.
        /// </summary>
        internal static string Παρακαλώ_επιλέξτε_πρώτα_μία_Νόσο___Αιτιολογία {
            get {
                return ResourceManager.GetString("Παρακαλώ επιλέξτε πρώτα μία Νόσο / Αιτιολογία", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ επιλέξτε πρώτα μία Παρούσα Νόσο.
        /// </summary>
        internal static string Παρακαλώ_επιλέξτε_πρώτα_μία_Παρούσα_Νόσο {
            get {
                return ResourceManager.GetString("Παρακαλώ επιλέξτε πρώτα μία Παρούσα Νόσο", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ επιλέξτε τον Φάκελο από τον οποίο θα γίνει η Εισαγωγή Βάσης Δεδομένων και Φωτογραφιών..
        /// </summary>
        internal static string Παρακαλώ_επιλέξτε_τον_Φάκελο_από_τον_οποίο_θα_γίνει_η_Εισαγωγή_Βάσης_Δεδομένων_και_Φωτογραφιών_ {
            get {
                return ResourceManager.GetString("Παρακαλώ επιλέξτε τον Φάκελο από τον οποίο θα γίνει η Εισαγωγή Βάσης Δεδομένων κα" +
                        "ι Φωτογραφιών.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ Όνομα και Επίθετο Πελάτη !.
        /// </summary>
        internal static string Παρακαλώ_Όνομα_και_Επίθετο_Πελάτη__ {
            get {
                return ResourceManager.GetString("Παρακαλώ Όνομα και Επίθετο Πελάτη !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ ορίστε καταρχήν τον Φάκελο των Φωτογραφιών και των Δεδομένων της Εφαρμογής.
        /// </summary>
        internal static string Παρακαλώ_ορίστε_καταρχήν_τον_Φάκελο_των_Φωτογραφιών_και_των_Δεδομένων_της_Εφαρμογής {
            get {
                return ResourceManager.GetString("Παρακαλώ ορίστε καταρχήν τον Φάκελο των Φωτογραφιών και των Δεδομένων της Εφαρμογ" +
                        "ής", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρακαλώ πρώτα επιλέξτε μία γραμμή στον πίνακα των Βιοψιών / Επεμβάσεων.
        /// </summary>
        internal static string Παρακαλώ_πρώτα_επιλέξτε_μία_γραμμή_στον_πίνακα_των_Βιοψιών___Επεμβάσεων {
            get {
                return ResourceManager.GetString("Παρακαλώ πρώτα επιλέξτε μία γραμμή στον πίνακα των Βιοψιών / Επεμβάσεων", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the Questionnaire !.
        /// </summary>
        internal static string Παρακαλώ_συμπληρώστε_το_ερωτηματολόγιο__ {
            get {
                return ResourceManager.GetString("Παρακαλώ συμπληρώστε το ερωτηματολόγιο !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-www-form-urlencoded.
        /// </summary>
        internal static string Παράμετροι_Μετρήσεως_Εικόνας {
            get {
                return ResourceManager.GetString("Παράμετροι Μετρήσεως Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρατηρούμε ότι δεν έχετε ορίσει ακόμα drives φωτογραφικών συσκευών.\nΠαρακαλώ ορίστε πρώτα drives φωτογραφικών συσκευών πριν εισάγετε φωτογραφίες από αυτές..
        /// </summary>
        internal static string Παρατηρούμε_ότι_δεν_έχετε_ορίσει_ακόμα_drives_φωτογραφικών_συσκευών__nΠαρακαλώ_ορίστε_πρώτα_drives_φωτογραφικών_συσκευών_πριν_εισάγετε_φωτογραφίες_από_αυτές_ {
            get {
                return ResourceManager.GetString("Παρατηρούμε ότι δεν έχετε ορίσει ακόμα drives φωτογραφικών συσκευών.\\nΠαρακαλώ ορ" +
                        "ίστε πρώτα drives φωτογραφικών συσκευών πριν εισάγετε φωτογραφίες από αυτές.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Παρούσα Νόσος.
        /// </summary>
        internal static string Παρούσα_Νόσος {
            get {
                return ResourceManager.GetString("Παρούσα Νόσος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πελάτες.
        /// </summary>
        internal static string Πελάτες {
            get {
                return ResourceManager.GetString("Πελάτες", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f8e8dFfYfly12eAADfdt1224.
        /// </summary>
        internal static string Περιγραφή_Ονόματος {
            get {
                return ResourceManager.GetString("Περιγραφή Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιέχει.
        /// </summary>
        internal static string Περιέχει {
            get {
                return ResourceManager.GetString("Περιέχει", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιέχουν.
        /// </summary>
        internal static string Περιέχουν {
            get {
                return ResourceManager.GetString("Περιέχουν", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |||12|||.
        /// </summary>
        internal static string Πηγή_Εικόνας {
            get {
                return ResourceManager.GetString("Πηγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πλαίσιο.
        /// </summary>
        internal static string Πλαίσιο {
            get {
                return ResourceManager.GetString("Πλαίσιο", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete completely ?.
        /// </summary>
        internal static string Πλήρη_διαγραφή__ {
            get {
                return ResourceManager.GetString("Πλήρη διαγραφή ;", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Photo completely ?.
        /// </summary>
        internal static string Πλήρη_Διαγραφή_Φωτογραφίας__ {
            get {
                return ResourceManager.GetString("Πλήρη Διαγραφή Φωτογραφίας ;", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\\.
        /// </summary>
        internal static string Προβολή_Εικόνας_1 {
            get {
                return ResourceManager.GetString("Προβολή Εικόνας 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\dtmsgbc.dll.
        /// </summary>
        internal static string Προβολή_Εικόνων {
            get {
                return ResourceManager.GetString("Προβολή Εικόνων", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Show.
        /// </summary>
        internal static string Προβολή_Παρουσίασης {
            get {
                return ResourceManager.GetString("Προβολή Παρουσίασης", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Photo.
        /// </summary>
        internal static string Πρώτη_Εικόνα {
            get {
                return ResourceManager.GetString("Πρώτη Εικόνα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στοιχεία Επικοινωνίας &amp; Σχόλια.
        /// </summary>
        internal static string Στοιχεία_Επικοινωνίας___Σχόλια {
            get {
                return ResourceManager.GetString("Στοιχεία Επικοινωνίας & Σχόλια", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string Σύκριση {
            get {
                return ResourceManager.GetString("Σύκριση", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while setting the Images Folder !.
        /// </summary>
        internal static string Συνέβη_ένα_Σφάλμα_κατά_τον_Ορισμό_του_Φακέλου_Φωτογραφιών__ {
            get {
                return ResourceManager.GetString("Συνέβη ένα Σφάλμα κατά τον Ορισμό του Φακέλου Φωτογραφιών !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Συνοδά Νοσήματα.
        /// </summary>
        internal static string Συνοδά_Νοσήματα {
            get {
                return ResourceManager.GetString("Συνοδά Νοσήματα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not send the Questionnaire.
        /// </summary>
        internal static string Σφάλμα__Δεν_ήταν_δυνατή_η_αποστολή_του_ερωτηματολογίου__ {
            get {
                return ResourceManager.GetString("Σφάλμα. Δεν ήταν δυνατή η αποστολή του ερωτηματολογίου !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.4dots-software.com/privacyhide/register.php.
        /// </summary>
        internal static string Σφάλμα_120 {
            get {
                return ResourceManager.GetString("Σφάλμα 120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;.
        /// </summary>
        internal static string Σφάλμα_1201 {
            get {
                return ResourceManager.GetString("Σφάλμα 1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not save Diagnosis.
        /// </summary>
        internal static string Σφάλμα_δεν_ήταν_δυνατή_η_αποθήκευση_της_Διάγνωσης {
            get {
                return ResourceManager.GetString("Σφάλμα δεν ήταν δυνατή η αποθήκευση της Διάγνωσης", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not save comments..
        /// </summary>
        internal static string Σφάλμα_δεν_ήταν_δυνατή_η_αποθήκευση_των_σχολίων {
            get {
                return ResourceManager.GetString("Σφάλμα δεν ήταν δυνατή η αποθήκευση των σχολίων", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Σχόλια {
            get {
                return ResourceManager.GetString("Σχόλια", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τελειώνει σε.
        /// </summary>
        internal static string Τελειώνει_σε {
            get {
                return ResourceManager.GetString("Τελειώνει σε", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τελειώνουν σε.
        /// </summary>
        internal static string Τελειώνουν_σε {
            get {
                return ResourceManager.GetString("Τελειώνουν σε", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τηλέφωνο.
        /// </summary>
        internal static string Τηλέφωνο {
            get {
                return ResourceManager.GetString("Τηλέφωνο", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 203023 DR-24031.
        /// </summary>
        internal static string Υπολογισμός_Επιφάνειας {
            get {
                return ResourceManager.GetString("Υπολογισμός Επιφάνειας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 56eft3fzazyef3er12zazTGD.
        /// </summary>
        internal static string Φίλτρο_Εικόνας {
            get {
                return ResourceManager.GetString("Φίλτρο Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        internal static string Φωτεινότητα {
            get {
                return ResourceManager.GetString("Φωτεινότητα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string Φωτογραφία {
            get {
                return ResourceManager.GetString("Φωτογραφία", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string Φωτογραφίες {
            get {
                return ResourceManager.GetString("Φωτογραφίες", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Photos.
        /// </summary>
        internal static string Φωτογραφίες_Πελάτη {
            get {
                return ResourceManager.GetString("Φωτογραφίες Πελάτη", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Χειρουργική Επέμβαση.
        /// </summary>
        internal static string Χειρουργική_Επέμβαση {
            get {
                return ResourceManager.GetString("Χειρουργική Επέμβαση", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Desktop Folder ?.
        /// </summary>
        internal static string Χρησιμοποίηση_Φακέλου_Επιφάνειας_Εργασίας__ {
            get {
                return ResourceManager.GetString("Χρησιμοποίηση Φακέλου Επιφάνειας Εργασίας ;", resourceCulture);
            }
        }
    }
}
